import assert from "node:assert/strict";
import test from "node:test";
import pg from "pg";

process.env.PGDATABASE ??= "personal_context";
process.env.EMBEDDINGS_ENABLED = "false";

const { Client } = await import("@modelcontextprotocol/sdk/client/index.js");
const { InMemoryTransport } = await import("@modelcontextprotocol/sdk/inMemory.js");
const { createServer, ActiveActorSession, requireActorIdentificationEnabled } = await import("../dist/mcp/server.js");
const {
    db,
    initializeDatabase,
    runDatabaseMigrations,
} = await import("../dist/storage/db.js");
const {
    actorPurgeConfirm,
    actorPurgePreview,
    identifyActor,
    deleteContext,
    getContext,
    getDatabaseMetadata,
    getUserProfile,
    listRecentContext,
    saveContext,
    searchContext,
    searchContextByVector,
    updateContext,
} = await import("../dist/mcp/tools.js");

function uniqueValue(prefix) {
    return `${prefix}-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

async function connectTestClient() {
    const server = createServer();
    const client = new Client({ name: "actor-attribution-test", version: "1.0.0" });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();

    await Promise.all([
        server.connect(serverTransport),
        client.connect(clientTransport),
    ]);

    return {
        client,
        server,
        async close() {
            await client.close();
            await server.close();
        },
    };
}

function textResult(result) {
    const item = result.content.find((content) => content.type === "text");
    assert.ok(item);
    return JSON.parse(item.text);
}

test("versioned migrations upgrade a legacy schema without attributing existing rows", async () => {
    const schema = uniqueValue("actor_migration").replaceAll("-", "_");
    const adminPool = new pg.Pool();
    await adminPool.query(`CREATE SCHEMA ${schema}`);
    const isolatedPool = new pg.Pool({ options: `-c search_path=${schema}` });

    try {
        await isolatedPool.query(`
            CREATE TABLE contexts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                kind TEXT NOT NULL DEFAULT 'note',
                content TEXT NOT NULL,
                source TEXT,
                tags TEXT[],
                created_at TIMESTAMPTZ NOT NULL,
                updated_at TIMESTAMPTZ NOT NULL
            );
            CREATE TABLE embeddings (
                context_id BIGINT PRIMARY KEY REFERENCES contexts(id) ON DELETE CASCADE,
                vector TEXT
            );
            INSERT INTO contexts (content, created_at, updated_at)
            VALUES ('legacy actor migration row', NOW(), NOW());
        `);

        await runDatabaseMigrations(isolatedPool);

        const legacy = await isolatedPool.query("SELECT actor_id, visibility, channel_id, group_id FROM contexts");
        const applied = await isolatedPool.query("SELECT version FROM schema_migrations ORDER BY version");
        assert.equal(legacy.rows[0].actor_id, null);
        assert.equal(legacy.rows[0].visibility, "whiteboard");
        assert.equal(legacy.rows[0].channel_id, null);
        assert.equal(legacy.rows[0].group_id, null);
        assert.deepEqual(applied.rows.map((row) => row.version), [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
    } finally {
        await isolatedPool.end();
        await adminPool.query(`DROP SCHEMA ${schema} CASCADE`);
        await adminPool.end();
    }
});

test("actor resolution is concurrency-safe and never merges name-only actors", async () => {
    await initializeDatabase();
    const externalId = uniqueValue("actor:test:concurrent");
    const [left, right] = await Promise.all([
        identifyActor({ external_id: externalId, name: "Concurrent Actor", kind: "ai" }),
        identifyActor({ external_id: externalId, name: "Ignored Duplicate Name", kind: "ai" }),
    ]);
    const firstNameOnly = await identifyActor({ name: "Same Display Name" });
    const secondNameOnly = await identifyActor({ name: "Same Display Name" });

    try {
        assert.equal(left.actor.id, right.actor.id);
        assert.equal(Number(left.created) + Number(right.created), 1);
        assert.notEqual(firstNameOnly.actor.id, secondNameOnly.actor.id);
    } finally {
        await db.query("DELETE FROM actors WHERE id = ANY($1::bigint[])", [[left.actor.id, firstNameOnly.actor.id, secondNameOnly.actor.id]]);
    }
});

test("active actor state is local and switchable", () => {
    const firstSession = new ActiveActorSession();
    const secondSession = new ActiveActorSession();

    firstSession.activate(10);
    assert.equal(firstSession.actorId, 10);
    assert.equal(secondSession.actorId, null);

    firstSession.activate(20);
    assert.equal(firstSession.actorId, 20);
});

test("identified, unidentified, strict, and switched MCP saves preserve compatibility", async () => {
    const firstExternalId = uniqueValue("actor:test:session-a");
    const secondExternalId = uniqueValue("actor:test:session-b");
    const unidentifiedText = uniqueValue("unidentified-save");
    const identifiedText = uniqueValue("identified-save");
    const switchedText = uniqueValue("switched-save");
    const connection = await connectTestClient();
    const savedIds = [];
    const actorIds = [];

    try {
        const unidentified = textResult(await connection.client.callTool({
            name: "save_context",
            arguments: { text: unidentifiedText },
        }));
        savedIds.push(unidentified.saved.id);
        assert.equal(unidentified.saved.actor, null);
        assert.equal(unidentified.warning.code, "ACTOR_NOT_IDENTIFIED");

        const firstIdentity = textResult(await connection.client.callTool({
            name: "identify_actor",
            arguments: { external_id: firstExternalId, name: "Session A", kind: "ai" },
        }));
        actorIds.push(firstIdentity.identified.actor.id);
        const identified = textResult(await connection.client.callTool({
            name: "save_context",
            arguments: { text: identifiedText },
        }));
        savedIds.push(identified.saved.id);
        assert.equal(identified.saved.actor.external_id, firstExternalId);
        assert.equal(identified.warning, undefined);

        const secondIdentity = textResult(await connection.client.callTool({
            name: "identify_actor",
            arguments: { external_id: secondExternalId, name: "Session B", kind: "human" },
        }));
        actorIds.push(secondIdentity.identified.actor.id);
        const switched = textResult(await connection.client.callTool({
            name: "save_context",
            arguments: { text: switchedText },
        }));
        savedIds.push(switched.saved.id);
        assert.equal(switched.saved.actor.external_id, secondExternalId);

        process.env.REQUIRE_ACTOR_IDENTIFICATION = "true";
        assert.equal(requireActorIdentificationEnabled(), true);
        const strictConnection = await connectTestClient();
        try {
            const strictResult = await strictConnection.client.callTool({
                name: "save_context",
                arguments: { text: uniqueValue("strict-rejected") },
            });
            assert.equal(strictResult.isError, true);
            const strictError = textResult(strictResult).error;
            assert.equal(strictError.code, "ACTOR_IDENTIFICATION_REQUIRED");
            assert.equal(strictError.required_action.tool, "save_context");
            assert.ok(strictError.required_action.include.actor.external_id);

            const strictRetry = textResult(await strictConnection.client.callTool({
                name: "save_context",
                arguments: {
                    text: uniqueValue("strict-retry"),
                    actor: {
                        external_id: uniqueValue("actor:test:strict-retry"),
                        name: "Strict Retry Actor",
                        kind: "ai",
                    },
                },
            }));
            savedIds.push(strictRetry.saved.id);
            actorIds.push(strictRetry.saved.actor.id);
            assert.equal(strictRetry.saved.actor.name, "Strict Retry Actor");
        } finally {
            await strictConnection.close();
        }
    } finally {
        delete process.env.REQUIRE_ACTOR_IDENTIFICATION;
        await connection.close();
        if (savedIds.length > 0) await db.query("DELETE FROM contexts WHERE id = ANY($1::bigint[])", [savedIds]);
        if (actorIds.length > 0) await db.query("DELETE FROM actors WHERE id = ANY($1::bigint[])", [actorIds]);
    }
});

test("self-contained saves survive client reconnects and resolve actors idempotently", async () => {
    const externalId = uniqueValue("actor:test:reconnect");
    const firstConnection = await connectTestClient();
    const secondConnection = await connectTestClient();
    const savedIds = [];
    let actorId;

    try {
        const firstSave = textResult(await firstConnection.client.callTool({
            name: "save_context",
            arguments: {
                text: uniqueValue("reconnect-first"),
                actor: { external_id: externalId, name: "Reconnect Actor", kind: "ai" },
            },
        }));
        savedIds.push(firstSave.saved.id);
        actorId = firstSave.saved.actor.id;
        assert.equal(firstSave.saved.actor.external_id, externalId);
        assert.equal(firstSave.actor_resolution.created, true);

        const secondSave = textResult(await secondConnection.client.callTool({
            name: "save_context",
            arguments: {
                text: uniqueValue("reconnect-second"),
                actor: { external_id: externalId, name: "Reconnect Actor", kind: "ai" },
            },
        }));
        savedIds.push(secondSave.saved.id);
        assert.equal(secondSave.saved.actor.id, actorId);
        assert.equal(secondSave.actor_resolution.created, false);
    } finally {
        await firstConnection.close();
        await secondConnection.close();
        if (savedIds.length > 0) await db.query("DELETE FROM contexts WHERE id = ANY($1::bigint[])", [savedIds]);
        if (actorId) await db.query("DELETE FROM actors WHERE id = $1", [actorId]);
    }
});

test("self-contained saves reject anonymous actor identities before writing", async () => {
    const actorName = uniqueValue("anonymous-self-contained");
    const connection = await connectTestClient();

    try {
        const result = await connection.client.callTool({
            name: "save_context",
            arguments: {
                text: uniqueValue("anonymous-self-contained-context"),
                actor: { name: actorName, kind: "ai" },
            },
        });
        assert.equal(result.isError, true);

        const actorCount = await db.query(
            "SELECT COUNT(*) AS matched FROM actors WHERE name = $1",
            [actorName],
        );
        assert.equal(Number(actorCount.rows[0].matched), 0);
    } finally {
        await connection.close();
    }
});

test("explicit save actor overrides and replaces the session-active actor", async () => {
    const sessionExternalId = uniqueValue("actor:test:precedence-session");
    const explicitExternalId = uniqueValue("actor:test:precedence-explicit");
    const connection = await connectTestClient();
    const savedIds = [];
    const actorIds = [];

    try {
        const sessionIdentity = textResult(await connection.client.callTool({
            name: "identify_actor",
            arguments: { external_id: sessionExternalId, name: "Session Actor", kind: "ai" },
        }));
        actorIds.push(sessionIdentity.identified.actor.id);

        const explicitSave = textResult(await connection.client.callTool({
            name: "save_context",
            arguments: {
                text: uniqueValue("precedence-explicit"),
                actor: { external_id: explicitExternalId, name: "Explicit Actor", kind: "ai" },
            },
        }));
        savedIds.push(explicitSave.saved.id);
        actorIds.push(explicitSave.saved.actor.id);
        assert.equal(explicitSave.saved.actor.external_id, explicitExternalId);

        const followingSave = textResult(await connection.client.callTool({
            name: "save_context",
            arguments: { text: uniqueValue("precedence-following") },
        }));
        savedIds.push(followingSave.saved.id);
        assert.equal(followingSave.saved.actor.external_id, explicitExternalId);
    } finally {
        await connection.close();
        if (savedIds.length > 0) await db.query("DELETE FROM contexts WHERE id = ANY($1::bigint[])", [savedIds]);
        if (actorIds.length > 0) await db.query("DELETE FROM actors WHERE id = ANY($1::bigint[])", [actorIds]);
    }
});

test("text, semantic, and recent queries filter inside the actor boundary", async () => {
    const firstExternalId = uniqueValue("actor:test:filter-a");
    const secondExternalId = uniqueValue("actor:test:filter-b");
    const marker = uniqueValue("actor-filter-marker");
    const firstActor = await identifyActor({ external_id: firstExternalId, name: "Filter A" });
    const secondActor = await identifyActor({ external_id: secondExternalId, name: "Filter B" });
    const firstContext = await saveContext(marker, [], "filter test", firstActor.actor.id);
    const secondContext = await saveContext(marker, [], "filter test", secondActor.actor.id);

    try {
        await db.query(
            `INSERT INTO embeddings (context_id, model, vector, created_at, updated_at)
             VALUES ($1, 'actor-test-model', '[1,0]', NOW(), NOW()),
                    ($2, 'actor-test-model', '[1,0]', NOW(), NOW())
             ON CONFLICT (context_id) DO UPDATE SET model = EXCLUDED.model, vector = EXCLUDED.vector`,
            [firstContext.id, secondContext.id],
        );

        const textResults = await searchContext(marker, 20, "low", firstExternalId);
        assert.deepEqual(textResults.map((context) => context.id), [firstContext.id]);

        const semanticResults = await searchContextByVector(
            marker,
            20,
            "low",
            secondExternalId,
            async () => ({ generated: true, model: "actor-test-model", vector: [1, 0] }),
        );
        assert.deepEqual(semanticResults.map((context) => context.id), [secondContext.id]);

        const recentResults = await listRecentContext(20, firstExternalId);
        assert.ok(recentResults.some((context) => context.id === firstContext.id));
        assert.ok(recentResults.every((context) => context.actor?.external_id === firstExternalId));
    } finally {
        await db.query("DELETE FROM contexts WHERE id = ANY($1::bigint[])", [[firstContext.id, secondContext.id]]);
        await db.query("DELETE FROM actors WHERE id = ANY($1::bigint[])", [[firstActor.actor.id, secondActor.actor.id]]);
    }
});

test("administrative context projections and metadata include actors", async () => {
    const externalId = uniqueValue("actor:test:admin");
    const identified = await identifyActor({ external_id: externalId, name: "Admin Projection" });
    const saved = await saveContext(uniqueValue("admin-projection"), [], undefined, identified.actor.id);

    try {
        const fetched = await getContext(saved.id);
        assert.equal(fetched.id, saved.id);
        assert.equal(fetched.content, saved.content);
        assert.equal(fetched.actor.external_id, externalId);
        assert.equal(await getContext(2_147_483_647), null);

        const updated = await updateContext(saved.id, "updated actor projection");
        assert.equal(updated.actor.external_id, externalId);

        const metadata = await getDatabaseMetadata();
        assert.ok(metadata.actor_count >= 1);
        assert.ok(metadata.tables.actors.bytes > 0);

        const deleted = await deleteContext(saved.id);
        assert.equal(deleted.actor.external_id, externalId);
    } finally {
        await db.query("DELETE FROM contexts WHERE id = $1", [saved.id]);
        await db.query("DELETE FROM actors WHERE id = $1", [identified.actor.id]);
    }
});

test("get_context returns an exact record or null", async () => {
    const marker = uniqueValue("get-context");
    const saved = await saveContext(marker, ["exact-id"], "get_context test");
    const connection = await connectTestClient();

    try {
        const found = textResult(await connection.client.callTool({
            name: "get_context",
            arguments: { id: saved.id },
        }));
        assert.equal(found.id, saved.id);
        assert.equal(found.context.id, saved.id);
        assert.equal(found.context.content, marker);
        assert.equal(found.context.visibility, "whiteboard");

        const missing = textResult(await connection.client.callTool({
            name: "get_context",
            arguments: { id: 2_147_483_647 },
        }));
        assert.equal(missing.id, 2_147_483_647);
        assert.equal(missing.context, null);
    } finally {
        await connection.close();
        await db.query("DELETE FROM contexts WHERE id = $1", [saved.id]);
    }
});

test("whiteboard is the only currently discoverable and writable visibility", async () => {
    const marker = uniqueValue("whiteboard-policy");
    const whiteboard = await saveContext(
        `${marker} shared`,
        ["profile", marker],
        "whiteboard policy test",
        null,
        "whiteboard",
    );
    const hidden = await db.query(
        `
            INSERT INTO contexts (
                kind,
                visibility,
                content,
                source,
                tags,
                created_at,
                updated_at
            )
            VALUES ('note', 'direct', $1, 'whiteboard policy test', $2, NOW(), NOW())
            RETURNING id
        `,
        [`${marker} hidden`, ["profile", marker]],
    );
    const hiddenId = Number(hidden.rows[0].id);

    try {
        assert.equal(whiteboard.visibility, "whiteboard");
        assert.equal((await getContext(whiteboard.id))?.id, whiteboard.id);
        assert.equal(await getContext(hiddenId), null);

        const searchResults = await searchContext(marker, 20, "low");
        assert.ok(searchResults.some((context) => context.id === whiteboard.id));
        assert.ok(searchResults.every((context) => context.id !== hiddenId));

        const recentResults = await listRecentContext(100);
        assert.ok(recentResults.some((context) => context.id === whiteboard.id));
        assert.ok(recentResults.every((context) => context.id !== hiddenId));

        const profile = await getUserProfile();
        assert.ok(profile.results.some((context) => context.id === whiteboard.id));
        assert.ok(profile.results.every((context) => context.id !== hiddenId));

        assert.equal(await updateContext(hiddenId, "must remain hidden"), null);
        assert.equal(await deleteContext(hiddenId), null);
    } finally {
        await db.query("DELETE FROM contexts WHERE id = ANY($1::bigint[])", [[whiteboard.id, hiddenId]]);
    }
});

test("actor purge removes only old anonymous unreferenced actors", async () => {
    const purgeable = await identifyActor({ name: uniqueValue("purgeable-anonymous") });
    const referenced = await identifyActor({ name: uniqueValue("referenced-anonymous") });
    const durable = await identifyActor({
        external_id: uniqueValue("actor:test:durable-orphan"),
        name: "Durable Orphan",
    });
    const referencedContext = await saveContext(
        uniqueValue("referenced-actor-context"),
        [],
        undefined,
        referenced.actor.id,
    );
    const actorIds = [purgeable.actor.id, referenced.actor.id, durable.actor.id];

    try {
        await db.query(
            "UPDATE actors SET last_seen_at = '2000-01-01T00:00:00.000Z' WHERE id = ANY($1::bigint[])",
            [actorIds],
        );

        const metadata = await getDatabaseMetadata();
        assert.ok(metadata.orphan_actor_count >= 2);
        assert.ok(metadata.purgeable_actor_count >= 1);

        const before = "2001-01-01T00:00:00.000Z";
        const preview = await actorPurgePreview(before);
        assert.equal(preview.scope, "anonymous_unreferenced_actors");
        assert.equal(preview.matched, 1);

        const purge = await actorPurgeConfirm(
            before,
            preview.confirmation_token,
            preview.matched,
        );
        assert.equal(purge.deleted_count, 1);
        assert.equal(purge.deleted[0].id, purgeable.actor.id);

        const survivors = await db.query(
            "SELECT id FROM actors WHERE id = ANY($1::bigint[]) ORDER BY id",
            [actorIds],
        );
        assert.deepEqual(
            survivors.rows.map((row) => Number(row.id)),
            [referenced.actor.id, durable.actor.id].sort((left, right) => left - right),
        );
    } finally {
        await db.query("DELETE FROM contexts WHERE id = $1", [referencedContext.id]);
        await db.query("DELETE FROM actors WHERE id = ANY($1::bigint[])", [actorIds]);
    }
});

test("user profile returns only explicitly tagged contexts", async () => {
    const marker = uniqueValue("profile-tag");
    const profileContext = await saveContext(`${marker} curated`, ["profile"]);
    const ordinaryContext = await saveContext(`${marker} ordinary`, ["history"]);

    try {
        const profile = await getUserProfile();
        assert.equal(profile.tag, "profile");
        assert.ok(profile.results.some((context) => context.id === profileContext.id));
        assert.ok(profile.results.every((context) => context.tags.includes("profile")));
        assert.ok(profile.results.every((context) => context.id !== ordinaryContext.id));
    } finally {
        await db.query("DELETE FROM contexts WHERE id = ANY($1::bigint[])", [[profileContext.id, ordinaryContext.id]]);
    }
});

test("built MCP schemas expose actor identification and stable actor filters", async () => {
    const connection = await connectTestClient();

    try {
        const { tools } = await connection.client.listTools();
        const byName = new Map(tools.map((tool) => [tool.name, tool]));
        const identifySchema = byName.get("identify_actor")?.inputSchema;
        const searchSchema = byName.get("search_context")?.inputSchema;
        const recentSchema = byName.get("list_recent_context")?.inputSchema;
        const getContextSchema = byName.get("get_context")?.inputSchema;
        const saveSchema = byName.get("save_context")?.inputSchema;
        const updateSchema = byName.get("update_context")?.inputSchema;

        assert.deepEqual(identifySchema.required, ["name"]);
        assert.ok(identifySchema.properties.external_id);
        assert.ok(searchSchema.properties.actor_external_id);
        assert.ok(recentSchema.properties.actor_external_id);
        assert.deepEqual(getContextSchema.required, ["id"]);
        assert.ok(getContextSchema.properties.id);
        assert.deepEqual(Object.keys(saveSchema.properties).sort(), ["actor", "source", "tags", "text", "visibility"]);
        assert.deepEqual(saveSchema.properties.visibility.enum, ["whiteboard"]);
        assert.deepEqual(saveSchema.properties.actor.required, ["external_id", "name"]);
        assert.ok(saveSchema.properties.actor.properties.external_id);
        assert.deepEqual(updateSchema.properties.visibility.enum, ["whiteboard"]);
        for (const toolName of [
            "create_channel",
            "add_channel_member",
            "remove_channel_member",
            "list_channels",
            "save_channel_context",
            "search_channel_context",
            "list_channel_context",
            "get_channel_context",
            "update_channel_context",
            "delete_channel_context",
            "create_access_group",
            "add_access_group_member",
            "remove_access_group_member",
            "list_access_groups",
            "save_group_context",
            "search_group_context",
            "list_group_context",
            "get_group_context",
            "update_group_context",
            "delete_group_context",
        ]) {
            const schema = byName.get(toolName)?.inputSchema;
            assert.ok(schema, `${toolName} must be registered`);
            assert.ok(schema.properties.auth, `${toolName} must expose explicit cryptographic auth`);
            assert.ok(!schema.required?.includes("auth"), `${toolName} must allow trusted tunnel-bound auth`);
        }
        for (const toolName of [
            "list_channels",
            "search_channel_context",
            "list_channel_context",
            "get_channel_context",
            "list_access_groups",
            "search_group_context",
            "list_group_context",
            "get_group_context",
        ]) {
            assert.deepEqual(
                byName.get(toolName)?.annotations,
                {
                    title: byName.get(toolName)?.annotations?.title,
                    readOnlyHint: true,
                    destructiveHint: false,
                    idempotentHint: true,
                    openWorldHint: false,
                },
                `${toolName} must advertise truthful closed-world read-only semantics`,
            );
            assert.ok(byName.get(toolName)?.annotations?.title);
        }
        for (const toolName of [
            "request_actor_session",
            "get_actor_session_request_status",
            "claim_actor_session",
        ]) {
            assert.ok(byName.get(toolName), `${toolName} must be registered`);
        }
        assert.ok(byName.get("actor_purge_preview"));
        assert.ok(byName.get("actor_purge_confirm"));
    } finally {
        await connection.close();
    }
});

test.after(async () => {
    await db.end();
});
