import assert from "node:assert/strict";
import test from "node:test";
import pg from "pg";

process.env.PGDATABASE ??= "personal_context";
process.env.EMBEDDINGS_ENABLED = "false";

const { Client } = await import("@modelcontextprotocol/sdk/client/index.js");
const { InMemoryTransport } = await import("@modelcontextprotocol/sdk/inMemory.js");
const { createServer, ActiveActorSession, requireActorIdentificationEnabled } = await import("../dist/mcp/server.js");
const {
    db,
    initializeDatabase,
    runDatabaseMigrations,
} = await import("../dist/storage/db.js");
const {
    identifyActor,
    deleteContext,
    getDatabaseMetadata,
    getUserProfile,
    listRecentContext,
    saveContext,
    searchContext,
    searchContextByVector,
    updateContext,
} = await import("../dist/mcp/tools.js");

function uniqueValue(prefix) {
    return `${prefix}-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

async function connectTestClient() {
    const server = createServer();
    const client = new Client({ name: "actor-attribution-test", version: "1.0.0" });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();

    await Promise.all([
        server.connect(serverTransport),
        client.connect(clientTransport),
    ]);

    return {
        client,
        server,
        async close() {
            await client.close();
            await server.close();
        },
    };
}

function textResult(result) {
    const item = result.content.find((content) => content.type === "text");
    assert.ok(item);
    return JSON.parse(item.text);
}

test("versioned migrations upgrade a legacy schema without attributing existing rows", async () => {
    const schema = uniqueValue("actor_migration").replaceAll("-", "_");
    const adminPool = new pg.Pool();
    await adminPool.query(`CREATE SCHEMA ${schema}`);
    const isolatedPool = new pg.Pool({ options: `-c search_path=${schema}` });

    try {
        await isolatedPool.query(`
            CREATE TABLE contexts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                kind TEXT NOT NULL DEFAULT 'note',
                content TEXT NOT NULL,
                source TEXT,
                tags TEXT[],
                created_at TIMESTAMPTZ NOT NULL,
                updated_at TIMESTAMPTZ NOT NULL
            );
            CREATE TABLE embeddings (
                context_id BIGINT PRIMARY KEY REFERENCES contexts(id) ON DELETE CASCADE,
                vector TEXT
            );
            INSERT INTO contexts (content, created_at, updated_at)
            VALUES ('legacy actor migration row', NOW(), NOW());
        `);

        await runDatabaseMigrations(isolatedPool);

        const legacy = await isolatedPool.query("SELECT actor_id FROM contexts");
        const applied = await isolatedPool.query("SELECT version FROM schema_migrations ORDER BY version");
        assert.equal(legacy.rows[0].actor_id, null);
        assert.deepEqual(applied.rows.map((row) => row.version), [1, 2]);
    } finally {
        await isolatedPool.end();
        await adminPool.query(`DROP SCHEMA ${schema} CASCADE`);
        await adminPool.end();
    }
});

test("actor resolution is concurrency-safe and never merges name-only actors", async () => {
    await initializeDatabase();
    const externalId = uniqueValue("actor:test:concurrent");
    const [left, right] = await Promise.all([
        identifyActor({ external_id: externalId, name: "Concurrent Actor", kind: "ai" }),
        identifyActor({ external_id: externalId, name: "Ignored Duplicate Name", kind: "ai" }),
    ]);
    const firstNameOnly = await identifyActor({ name: "Same Display Name" });
    const secondNameOnly = await identifyActor({ name: "Same Display Name" });

    try {
        assert.equal(left.actor.id, right.actor.id);
        assert.equal(Number(left.created) + Number(right.created), 1);
        assert.notEqual(firstNameOnly.actor.id, secondNameOnly.actor.id);
    } finally {
        await db.query("DELETE FROM actors WHERE id = ANY($1::bigint[])", [[left.actor.id, firstNameOnly.actor.id, secondNameOnly.actor.id]]);
    }
});

test("active actor state is local and switchable", () => {
    const firstSession = new ActiveActorSession();
    const secondSession = new ActiveActorSession();

    firstSession.activate(10);
    assert.equal(firstSession.actorId, 10);
    assert.equal(secondSession.actorId, null);

    firstSession.activate(20);
    assert.equal(firstSession.actorId, 20);
});

test("identified, unidentified, strict, and switched MCP saves preserve compatibility", async () => {
    const firstExternalId = uniqueValue("actor:test:session-a");
    const secondExternalId = uniqueValue("actor:test:session-b");
    const unidentifiedText = uniqueValue("unidentified-save");
    const identifiedText = uniqueValue("identified-save");
    const switchedText = uniqueValue("switched-save");
    const connection = await connectTestClient();
    const savedIds = [];
    const actorIds = [];

    try {
        const unidentified = textResult(await connection.client.callTool({
            name: "save_context",
            arguments: { text: unidentifiedText },
        }));
        savedIds.push(unidentified.saved.id);
        assert.equal(unidentified.saved.actor, null);
        assert.equal(unidentified.warning.code, "ACTOR_NOT_IDENTIFIED");

        const firstIdentity = textResult(await connection.client.callTool({
            name: "identify_actor",
            arguments: { external_id: firstExternalId, name: "Session A", kind: "ai" },
        }));
        actorIds.push(firstIdentity.identified.actor.id);
        const identified = textResult(await connection.client.callTool({
            name: "save_context",
            arguments: { text: identifiedText },
        }));
        savedIds.push(identified.saved.id);
        assert.equal(identified.saved.actor.external_id, firstExternalId);
        assert.equal(identified.warning, undefined);

        const secondIdentity = textResult(await connection.client.callTool({
            name: "identify_actor",
            arguments: { external_id: secondExternalId, name: "Session B", kind: "human" },
        }));
        actorIds.push(secondIdentity.identified.actor.id);
        const switched = textResult(await connection.client.callTool({
            name: "save_context",
            arguments: { text: switchedText },
        }));
        savedIds.push(switched.saved.id);
        assert.equal(switched.saved.actor.external_id, secondExternalId);

        process.env.REQUIRE_ACTOR_IDENTIFICATION = "true";
        assert.equal(requireActorIdentificationEnabled(), true);
        const strictConnection = await connectTestClient();
        try {
            const strictResult = await strictConnection.client.callTool({
                name: "save_context",
                arguments: { text: uniqueValue("strict-rejected") },
            });
            assert.equal(strictResult.isError, true);
            assert.equal(textResult(strictResult).error.code, "ACTOR_IDENTIFICATION_REQUIRED");
        } finally {
            await strictConnection.close();
        }
    } finally {
        delete process.env.REQUIRE_ACTOR_IDENTIFICATION;
        await connection.close();
        if (savedIds.length > 0) await db.query("DELETE FROM contexts WHERE id = ANY($1::bigint[])", [savedIds]);
        if (actorIds.length > 0) await db.query("DELETE FROM actors WHERE id = ANY($1::bigint[])", [actorIds]);
    }
});

test("text, semantic, and recent queries filter inside the actor boundary", async () => {
    const firstExternalId = uniqueValue("actor:test:filter-a");
    const secondExternalId = uniqueValue("actor:test:filter-b");
    const marker = uniqueValue("actor-filter-marker");
    const firstActor = await identifyActor({ external_id: firstExternalId, name: "Filter A" });
    const secondActor = await identifyActor({ external_id: secondExternalId, name: "Filter B" });
    const firstContext = await saveContext(marker, [], "filter test", firstActor.actor.id);
    const secondContext = await saveContext(marker, [], "filter test", secondActor.actor.id);

    try {
        await db.query(
            `INSERT INTO embeddings (context_id, model, vector, created_at, updated_at)
             VALUES ($1, 'actor-test-model', '[1,0]', NOW(), NOW()),
                    ($2, 'actor-test-model', '[1,0]', NOW(), NOW())
             ON CONFLICT (context_id) DO UPDATE SET model = EXCLUDED.model, vector = EXCLUDED.vector`,
            [firstContext.id, secondContext.id],
        );

        const textResults = await searchContext(marker, 20, "low", firstExternalId);
        assert.deepEqual(textResults.map((context) => context.id), [firstContext.id]);

        const semanticResults = await searchContextByVector(
            marker,
            20,
            "low",
            secondExternalId,
            async () => ({ generated: true, model: "actor-test-model", vector: [1, 0] }),
        );
        assert.deepEqual(semanticResults.map((context) => context.id), [secondContext.id]);

        const recentResults = await listRecentContext(20, firstExternalId);
        assert.ok(recentResults.some((context) => context.id === firstContext.id));
        assert.ok(recentResults.every((context) => context.actor?.external_id === firstExternalId));
    } finally {
        await db.query("DELETE FROM contexts WHERE id = ANY($1::bigint[])", [[firstContext.id, secondContext.id]]);
        await db.query("DELETE FROM actors WHERE id = ANY($1::bigint[])", [[firstActor.actor.id, secondActor.actor.id]]);
    }
});

test("administrative context projections and metadata include actors", async () => {
    const externalId = uniqueValue("actor:test:admin");
    const identified = await identifyActor({ external_id: externalId, name: "Admin Projection" });
    const saved = await saveContext(uniqueValue("admin-projection"), [], undefined, identified.actor.id);

    try {
        const updated = await updateContext(saved.id, "updated actor projection");
        assert.equal(updated.actor.external_id, externalId);

        const metadata = await getDatabaseMetadata();
        assert.ok(metadata.actor_count >= 1);
        assert.ok(metadata.tables.actors.bytes > 0);

        const deleted = await deleteContext(saved.id);
        assert.equal(deleted.actor.external_id, externalId);
    } finally {
        await db.query("DELETE FROM contexts WHERE id = $1", [saved.id]);
        await db.query("DELETE FROM actors WHERE id = $1", [identified.actor.id]);
    }
});

test("user profile returns only explicitly tagged contexts", async () => {
    const marker = uniqueValue("profile-tag");
    const profileContext = await saveContext(`${marker} curated`, ["profile"]);
    const ordinaryContext = await saveContext(`${marker} ordinary`, ["history"]);

    try {
        const profile = await getUserProfile();
        assert.equal(profile.tag, "profile");
        assert.ok(profile.results.some((context) => context.id === profileContext.id));
        assert.ok(profile.results.every((context) => context.tags.includes("profile")));
        assert.ok(profile.results.every((context) => context.id !== ordinaryContext.id));
    } finally {
        await db.query("DELETE FROM contexts WHERE id = ANY($1::bigint[])", [[profileContext.id, ordinaryContext.id]]);
    }
});

test("built MCP schemas expose actor identification and stable actor filters", async () => {
    const connection = await connectTestClient();

    try {
        const { tools } = await connection.client.listTools();
        const byName = new Map(tools.map((tool) => [tool.name, tool]));
        const identifySchema = byName.get("identify_actor")?.inputSchema;
        const searchSchema = byName.get("search_context")?.inputSchema;
        const recentSchema = byName.get("list_recent_context")?.inputSchema;
        const saveSchema = byName.get("save_context")?.inputSchema;

        assert.deepEqual(identifySchema.required, ["name"]);
        assert.ok(identifySchema.properties.external_id);
        assert.ok(searchSchema.properties.actor_external_id);
        assert.ok(recentSchema.properties.actor_external_id);
        assert.deepEqual(Object.keys(saveSchema.properties).sort(), ["source", "tags", "text"]);
    } finally {
        await connection.close();
    }
});

test.after(async () => {
    await db.end();
});
