import pg from "pg";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";
import type { PoolConfig } from "pg";

const { Pool } = pg;

function loadDotEnv(envPath = resolve(process.cwd(), ".env")) {
    if (!existsSync(envPath)) {
        return;
    }

    const envFile = readFileSync(envPath, "utf8");

    for (const line of envFile.split(/\r?\n/)) {
        const trimmedLine = line.trim();

        if (!trimmedLine || trimmedLine.startsWith("#")) {
            continue;
        }

        const separatorIndex = trimmedLine.indexOf("=");

        if (separatorIndex === -1) {
            continue;
        }

        const key = trimmedLine.slice(0, separatorIndex).trim();
        let value = trimmedLine.slice(separatorIndex + 1).trim();

        if (!key || process.env[key] !== undefined) {
            continue;
        }

        if (
            (value.startsWith("\"") && value.endsWith("\"")) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            value = value.slice(1, -1);
        }

        process.env[key] = value;
    }
}

function configFromDatabaseUrl(databaseUrl: string): PoolConfig {
    const url = new URL(databaseUrl);
    const config: PoolConfig = {};

    if (url.hostname) {
        config.host = url.hostname;
    }

    if (url.port) {
        config.port = Number.parseInt(url.port, 10);
    }

    if (url.pathname && url.pathname !== "/") {
        config.database = decodeURIComponent(url.pathname.slice(1));
    }

    if (url.username) {
        config.user = decodeURIComponent(url.username);
    }

    if (url.password) {
        config.password = decodeURIComponent(url.password);
    }

    return config;
}

function getDatabaseConfig(): PoolConfig {
    loadDotEnv();

    const databaseUrl = process.env.DATABASE_URL?.trim();
    const config: PoolConfig = databaseUrl ? configFromDatabaseUrl(databaseUrl) : {};

    if (process.env.PGHOST) {
        config.host = process.env.PGHOST;
    }

    if (process.env.PGPORT) {
        config.port = Number.parseInt(process.env.PGPORT, 10);
    }

    if (process.env.PGDATABASE) {
        config.database = process.env.PGDATABASE;
    }

    if (process.env.PGUSER) {
        config.user = process.env.PGUSER;
    }

    if (process.env.PGPASSWORD !== undefined) {
        config.password = process.env.PGPASSWORD;
    }

    if (!config.connectionString && !config.database) {
        throw new Error("Set DATABASE_URL or PGDATABASE in the environment or .env file.");
    }

    return config;
}

export const db = new Pool(getDatabaseConfig());

type Migration = {
    version: number;
    name: string;
    sql: string;
};

const migrations: Migration[] = [
    {
        version: 1,
        name: "initial_context_schema",
        sql: `
            CREATE TABLE IF NOT EXISTS contexts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                kind TEXT NOT NULL DEFAULT 'note',
                content TEXT NOT NULL,
                source TEXT,
                tags TEXT[],
                created_at TIMESTAMPTZ NOT NULL,
                updated_at TIMESTAMPTZ NOT NULL
            );

            CREATE TABLE IF NOT EXISTS embeddings (
                context_id BIGINT PRIMARY KEY REFERENCES contexts(id) ON DELETE CASCADE,
                model TEXT,
                vector TEXT,
                created_at TIMESTAMPTZ,
                updated_at TIMESTAMPTZ
            );

            ALTER TABLE embeddings ADD COLUMN IF NOT EXISTS model TEXT;
            ALTER TABLE embeddings ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
            ALTER TABLE embeddings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

            CREATE INDEX IF NOT EXISTS contexts_created_at_idx
                ON contexts(created_at DESC, id DESC);

            CREATE INDEX IF NOT EXISTS contexts_tags_idx
                ON contexts USING GIN(tags);
        `,
    },
    {
        version: 2,
        name: "actor_attribution",
        sql: `
            CREATE TABLE IF NOT EXISTS actors (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                external_id TEXT,
                name TEXT NOT NULL,
                kind TEXT,
                metadata JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE UNIQUE INDEX IF NOT EXISTS actors_external_id_unique_idx
                ON actors(external_id)
                WHERE external_id IS NOT NULL;

            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS actor_id BIGINT;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'contexts_actor_id_fkey'
                      AND conrelid = 'contexts'::regclass
                ) THEN
                    ALTER TABLE contexts
                        ADD CONSTRAINT contexts_actor_id_fkey
                        FOREIGN KEY (actor_id)
                        REFERENCES actors(id)
                        ON DELETE SET NULL;
                END IF;
            END
            $$;

            CREATE INDEX IF NOT EXISTS contexts_actor_created_at_idx
                ON contexts(actor_id, created_at DESC, id DESC);
        `,
    },
    {
        version: 3,
        name: "context_visibility",
        sql: `
            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'whiteboard';

            ALTER TABLE contexts
                DROP CONSTRAINT IF EXISTS contexts_visibility_check;

            ALTER TABLE contexts
                ADD CONSTRAINT contexts_visibility_check
                CHECK (visibility IN ('whiteboard', 'channel', 'direct', 'personal', 'system'));

            CREATE INDEX IF NOT EXISTS contexts_visibility_created_at_idx
                ON contexts(visibility, created_at DESC, id DESC);
        `,
    },
];

let initializationPromise: Promise<void> | undefined;

export async function initializeDatabase() {
    initializationPromise ??= runDatabaseMigrations().catch((error) => {
        initializationPromise = undefined;
        throw error;
    });

    await initializationPromise;
}

export async function runDatabaseMigrations(pool: pg.Pool = db) {
    const client = await pool.connect();

    try {
        await client.query(`
            CREATE TABLE IF NOT EXISTS schema_migrations (
                version INTEGER PRIMARY KEY,
                name TEXT NOT NULL,
                applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);

        for (const migration of migrations) {
            await client.query("BEGIN");

            try {
                await client.query(
                    "SELECT pg_advisory_xact_lock(hashtext('personal-context-server-schema-migrations'))"
                );
                const applied = await client.query(
                    "SELECT 1 FROM schema_migrations WHERE version = $1",
                    [migration.version]
                );

                if (applied.rowCount === 0) {
                    await client.query(migration.sql);
                    await client.query(
                        "INSERT INTO schema_migrations (version, name) VALUES ($1, $2)",
                        [migration.version, migration.name]
                    );
                }

                await client.query("COMMIT");
            } catch (error) {
                await client.query("ROLLBACK");
                throw error;
            }
        }
    } finally {
        client.release();
    }
}

export async function verifyDatabaseConnection() {
    let client: pg.PoolClient;

    try {
        client = await db.connect();
    } catch (error) {
        if (
            error instanceof Error &&
            error.message.includes("client password must be a string")
        ) {
            throw new Error(
                "Postgres requires password authentication. Add a password to DATABASE_URL or set PGPASSWORD in the environment or .env file.",
                { cause: error }
            );
        }

        throw error;
    }

    try {
        await client.query("SELECT 1");
    } finally {
        client.release();
    }
}

function isDirectRun() {
    if (!process.argv[1]) {
        return false;
    }

    return fileURLToPath(import.meta.url) === resolve(process.argv[1]);
}

async function main() {
    try {
        await verifyDatabaseConnection();
        console.log("Database connection ok.");
    } finally {
        await db.end();
    }
}

if (isDirectRun()) {
    main().catch((error: unknown) => {
        console.error(error instanceof Error ? error.message : error);
        process.exitCode = 1;
    });
}
