import pg from "pg";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";
import type { PoolConfig } from "pg";

const { Pool } = pg;

function loadDotEnv(envPath = resolve(process.cwd(), ".env")) {
    if (!existsSync(envPath)) {
        return;
    }

    const envFile = readFileSync(envPath, "utf8");

    for (const line of envFile.split(/\r?\n/)) {
        const trimmedLine = line.trim();

        if (!trimmedLine || trimmedLine.startsWith("#")) {
            continue;
        }

        const separatorIndex = trimmedLine.indexOf("=");

        if (separatorIndex === -1) {
            continue;
        }

        const key = trimmedLine.slice(0, separatorIndex).trim();
        let value = trimmedLine.slice(separatorIndex + 1).trim();

        if (!key || process.env[key] !== undefined) {
            continue;
        }

        if (
            (value.startsWith("\"") && value.endsWith("\"")) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            value = value.slice(1, -1);
        }

        process.env[key] = value;
    }
}

function configFromDatabaseUrl(databaseUrl: string): PoolConfig {
    const url = new URL(databaseUrl);
    const config: PoolConfig = {};

    if (url.hostname) {
        config.host = url.hostname;
    }

    if (url.port) {
        config.port = Number.parseInt(url.port, 10);
    }

    if (url.pathname && url.pathname !== "/") {
        config.database = decodeURIComponent(url.pathname.slice(1));
    }

    if (url.username) {
        config.user = decodeURIComponent(url.username);
    }

    if (url.password) {
        config.password = decodeURIComponent(url.password);
    }

    return config;
}

function getDatabaseConfig(): PoolConfig {
    loadDotEnv();

    const databaseUrl = process.env.DATABASE_URL?.trim();
    const config: PoolConfig = databaseUrl ? configFromDatabaseUrl(databaseUrl) : {};

    if (process.env.PGHOST) {
        config.host = process.env.PGHOST;
    }

    if (process.env.PGPORT) {
        config.port = Number.parseInt(process.env.PGPORT, 10);
    }

    if (process.env.PGDATABASE) {
        config.database = process.env.PGDATABASE;
    }

    if (process.env.PGUSER) {
        config.user = process.env.PGUSER;
    }

    if (process.env.PGPASSWORD !== undefined) {
        config.password = process.env.PGPASSWORD;
    }

    if (!config.connectionString && !config.database) {
        throw new Error("Set DATABASE_URL or PGDATABASE in the environment or .env file.");
    }

    return config;
}

export const db = new Pool(getDatabaseConfig());

type Migration = {
    version: number;
    name: string;
    sql: string;
};

const migrations: Migration[] = [
    {
        version: 1,
        name: "initial_context_schema",
        sql: `
            CREATE TABLE IF NOT EXISTS contexts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                kind TEXT NOT NULL DEFAULT 'note',
                content TEXT NOT NULL,
                source TEXT,
                tags TEXT[],
                created_at TIMESTAMPTZ NOT NULL,
                updated_at TIMESTAMPTZ NOT NULL
            );

            CREATE TABLE IF NOT EXISTS embeddings (
                context_id BIGINT PRIMARY KEY REFERENCES contexts(id) ON DELETE CASCADE,
                model TEXT,
                vector TEXT,
                created_at TIMESTAMPTZ,
                updated_at TIMESTAMPTZ
            );

            ALTER TABLE embeddings ADD COLUMN IF NOT EXISTS model TEXT;
            ALTER TABLE embeddings ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
            ALTER TABLE embeddings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

            CREATE INDEX IF NOT EXISTS contexts_created_at_idx
                ON contexts(created_at DESC, id DESC);

            CREATE INDEX IF NOT EXISTS contexts_tags_idx
                ON contexts USING GIN(tags);
        `,
    },
    {
        version: 2,
        name: "actor_attribution",
        sql: `
            CREATE TABLE IF NOT EXISTS actors (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                external_id TEXT,
                name TEXT NOT NULL,
                kind TEXT,
                metadata JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE UNIQUE INDEX IF NOT EXISTS actors_external_id_unique_idx
                ON actors(external_id)
                WHERE external_id IS NOT NULL;

            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS actor_id BIGINT;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'contexts_actor_id_fkey'
                      AND conrelid = 'contexts'::regclass
                ) THEN
                    ALTER TABLE contexts
                        ADD CONSTRAINT contexts_actor_id_fkey
                        FOREIGN KEY (actor_id)
                        REFERENCES actors(id)
                        ON DELETE SET NULL;
                END IF;
            END
            $$;

            CREATE INDEX IF NOT EXISTS contexts_actor_created_at_idx
                ON contexts(actor_id, created_at DESC, id DESC);
        `,
    },
    {
        version: 3,
        name: "context_visibility",
        sql: `
            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'whiteboard';

            ALTER TABLE contexts
                DROP CONSTRAINT IF EXISTS contexts_visibility_check;

            ALTER TABLE contexts
                ADD CONSTRAINT contexts_visibility_check
                CHECK (visibility IN ('whiteboard', 'channel', 'direct', 'personal', 'system'));

            CREATE INDEX IF NOT EXISTS contexts_visibility_created_at_idx
                ON contexts(visibility, created_at DESC, id DESC);
        `,
    },
    {
        version: 4,
        name: "authenticated_channels",
        sql: `
            CREATE TABLE IF NOT EXISTS actor_keys (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key_id TEXT NOT NULL UNIQUE,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                label TEXT,
                algorithm TEXT NOT NULL DEFAULT 'ed25519',
                public_key_pem TEXT NOT NULL,
                fingerprint_sha256 TEXT NOT NULL UNIQUE,
                status TEXT NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'revoked')),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                revoked_at TIMESTAMPTZ
            );

            CREATE INDEX IF NOT EXISTS actor_keys_actor_status_idx
                ON actor_keys(actor_id, status);

            CREATE TABLE IF NOT EXISTS auth_nonces (
                key_id TEXT NOT NULL REFERENCES actor_keys(key_id) ON DELETE CASCADE,
                nonce TEXT NOT NULL,
                used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                expires_at TIMESTAMPTZ NOT NULL,
                PRIMARY KEY (key_id, nonce)
            );

            CREATE INDEX IF NOT EXISTS auth_nonces_expires_at_idx
                ON auth_nonces(expires_at);

            CREATE TABLE IF NOT EXISTS channels (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                slug TEXT NOT NULL UNIQUE,
                name TEXT NOT NULL,
                description TEXT,
                created_by_actor_id BIGINT NOT NULL REFERENCES actors(id),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE IF NOT EXISTS channel_memberships (
                channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                role TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member')),
                can_read BOOLEAN NOT NULL DEFAULT TRUE,
                can_write BOOLEAN NOT NULL DEFAULT TRUE,
                joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                removed_at TIMESTAMPTZ,
                PRIMARY KEY (channel_id, actor_id)
            );

            CREATE INDEX IF NOT EXISTS channel_memberships_actor_active_idx
                ON channel_memberships(actor_id, channel_id)
                WHERE removed_at IS NULL;

            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS channel_id BIGINT;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'contexts_channel_id_fkey'
                      AND conrelid = 'contexts'::regclass
                ) THEN
                    ALTER TABLE contexts
                        ADD CONSTRAINT contexts_channel_id_fkey
                        FOREIGN KEY (channel_id)
                        REFERENCES channels(id)
                        ON DELETE RESTRICT;
                END IF;
            END
            $$;

            ALTER TABLE contexts
                DROP CONSTRAINT IF EXISTS contexts_visibility_scope_check;

            ALTER TABLE contexts
                ADD CONSTRAINT contexts_visibility_scope_check
                CHECK (
                    (visibility = 'channel' AND channel_id IS NOT NULL)
                    OR (visibility <> 'channel' AND channel_id IS NULL)
                );

            CREATE INDEX IF NOT EXISTS contexts_channel_created_at_idx
                ON contexts(channel_id, created_at DESC, id DESC)
                WHERE visibility = 'channel';
        `,
    },
    {
        version: 5,
        name: "approved_actor_sessions",
        sql: `
            CREATE TABLE IF NOT EXISTS actor_session_requests (
                request_id TEXT PRIMARY KEY,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                client_label TEXT,
                claim_secret_hash TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'approved', 'claimed', 'denied', 'expired')),
                requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                request_expires_at TIMESTAMPTZ NOT NULL,
                approved_at TIMESTAMPTZ,
                approved_session_ttl_seconds INTEGER,
                claimed_at TIMESTAMPTZ,
                denied_at TIMESTAMPTZ
            );

            CREATE INDEX IF NOT EXISTS actor_session_requests_status_expiry_idx
                ON actor_session_requests(status, request_expires_at);

            CREATE TABLE IF NOT EXISTS actor_sessions (
                session_id TEXT PRIMARY KEY,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                token_hash TEXT NOT NULL UNIQUE,
                client_label TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                expires_at TIMESTAMPTZ NOT NULL,
                last_used_at TIMESTAMPTZ,
                revoked_at TIMESTAMPTZ
            );

            CREATE INDEX IF NOT EXISTS actor_sessions_actor_active_idx
                ON actor_sessions(actor_id, expires_at)
                WHERE revoked_at IS NULL;

            CREATE TABLE IF NOT EXISTS actor_session_nonces (
                session_id TEXT NOT NULL REFERENCES actor_sessions(session_id) ON DELETE CASCADE,
                nonce TEXT NOT NULL,
                used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                expires_at TIMESTAMPTZ NOT NULL,
                PRIMARY KEY (session_id, nonce)
            );

            CREATE INDEX IF NOT EXISTS actor_session_nonces_expires_at_idx
                ON actor_session_nonces(expires_at);
        `,
    },
    {
        version: 6,
        name: "single_active_actor_session",
        sql: `
            ALTER TABLE actor_sessions
                ADD COLUMN IF NOT EXISTS predecessor_session_id TEXT,
                ADD COLUMN IF NOT EXISTS replaced_by_session_id TEXT,
                ADD COLUMN IF NOT EXISTS revocation_reason TEXT;

            WITH ranked AS (
                SELECT
                    session_id,
                    ROW_NUMBER() OVER (
                        PARTITION BY actor_id
                        ORDER BY created_at DESC, session_id DESC
                    ) AS active_rank
                FROM actor_sessions
                WHERE revoked_at IS NULL
            )
            UPDATE actor_sessions
            SET
                revoked_at = NOW(),
                revocation_reason = 'superseded_during_migration'
            FROM ranked
            WHERE actor_sessions.session_id = ranked.session_id
              AND ranked.active_rank > 1;

            CREATE UNIQUE INDEX IF NOT EXISTS actor_sessions_one_active_per_actor_idx
                ON actor_sessions(actor_id)
                WHERE revoked_at IS NULL;
        `,
    },
    {
        version: 7,
        name: "openai_tunnel_actor_sessions",
        sql: `
            ALTER TABLE actor_session_requests
                ADD COLUMN IF NOT EXISTS activation_pin_hash TEXT;

            ALTER TABLE actor_sessions
                ADD COLUMN IF NOT EXISTS openai_subject_hash TEXT,
                ADD COLUMN IF NOT EXISTS openai_session_hash TEXT;

            CREATE INDEX IF NOT EXISTS actor_sessions_openai_binding_idx
                ON actor_sessions(openai_subject_hash, openai_session_hash)
                WHERE openai_subject_hash IS NOT NULL
                  AND openai_session_hash IS NOT NULL;
        `,
    },
    {
        version: 8,
        name: "bind_openai_identity_at_session_request",
        sql: `
            ALTER TABLE actor_session_requests
                ADD COLUMN IF NOT EXISTS openai_subject_hash TEXT,
                ADD COLUMN IF NOT EXISTS openai_session_hash TEXT;
        `,
    },
    {
        version: 9,
        name: "access_groups",
        sql: `
            CREATE TABLE IF NOT EXISTS access_groups (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                slug TEXT NOT NULL UNIQUE,
                name TEXT NOT NULL,
                description TEXT,
                created_by_actor_id BIGINT NOT NULL REFERENCES actors(id),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE IF NOT EXISTS access_group_memberships (
                group_id BIGINT NOT NULL REFERENCES access_groups(id) ON DELETE CASCADE,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                role TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member')),
                can_read BOOLEAN NOT NULL DEFAULT TRUE,
                can_write BOOLEAN NOT NULL DEFAULT TRUE,
                joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                removed_at TIMESTAMPTZ,
                PRIMARY KEY (group_id, actor_id)
            );

            CREATE INDEX IF NOT EXISTS access_group_memberships_actor_active_idx
                ON access_group_memberships(actor_id, group_id)
                WHERE removed_at IS NULL;

            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS group_id BIGINT;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'contexts_group_id_fkey'
                      AND conrelid = 'contexts'::regclass
                ) THEN
                    ALTER TABLE contexts
                        ADD CONSTRAINT contexts_group_id_fkey
                        FOREIGN KEY (group_id)
                        REFERENCES access_groups(id)
                        ON DELETE RESTRICT;
                END IF;
            END
            $$;

            ALTER TABLE contexts
                DROP CONSTRAINT IF EXISTS contexts_visibility_check;

            ALTER TABLE contexts
                ADD CONSTRAINT contexts_visibility_check
                CHECK (visibility IN ('whiteboard', 'channel', 'direct', 'personal', 'system', 'group'));

            ALTER TABLE contexts
                DROP CONSTRAINT IF EXISTS contexts_visibility_scope_check;

            ALTER TABLE contexts
                ADD CONSTRAINT contexts_visibility_scope_check
                CHECK (
                    (visibility = 'channel' AND channel_id IS NOT NULL AND group_id IS NULL)
                    OR (visibility = 'group' AND group_id IS NOT NULL AND channel_id IS NULL)
                    OR (visibility NOT IN ('channel', 'group') AND channel_id IS NULL AND group_id IS NULL)
                );

            CREATE INDEX IF NOT EXISTS contexts_group_created_at_idx
                ON contexts(group_id, created_at DESC, id DESC)
                WHERE visibility = 'group';
        `,
    },
];

let initializationPromise: Promise<void> | undefined;

export async function initializeDatabase() {
    initializationPromise ??= runDatabaseMigrations().catch((error) => {
        initializationPromise = undefined;
        throw error;
    });

    await initializationPromise;
}

export async function runDatabaseMigrations(pool: pg.Pool = db) {
    const client = await pool.connect();

    try {
        await client.query(`
            CREATE TABLE IF NOT EXISTS schema_migrations (
                version INTEGER PRIMARY KEY,
                name TEXT NOT NULL,
                applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);

        for (const migration of migrations) {
            await client.query("BEGIN");

            try {
                await client.query(
                    "SELECT pg_advisory_xact_lock(hashtext('personal-context-server-schema-migrations'))"
                );
                const applied = await client.query(
                    "SELECT 1 FROM schema_migrations WHERE version = $1",
                    [migration.version]
                );

                if (applied.rowCount === 0) {
                    await client.query(migration.sql);
                    await client.query(
                        "INSERT INTO schema_migrations (version, name) VALUES ($1, $2)",
                        [migration.version, migration.name]
                    );
                }

                await client.query("COMMIT");
            } catch (error) {
                await client.query("ROLLBACK");
                throw error;
            }
        }
    } finally {
        client.release();
    }
}

export async function verifyDatabaseConnection() {
    let client: pg.PoolClient;

    try {
        client = await db.connect();
    } catch (error) {
        if (
            error instanceof Error &&
            error.message.includes("client password must be a string")
        ) {
            throw new Error(
                "Postgres requires password authentication. Add a password to DATABASE_URL or set PGPASSWORD in the environment or .env file.",
                { cause: error }
            );
        }

        throw error;
    }

    try {
        await client.query("SELECT 1");
    } finally {
        client.release();
    }
}

function isDirectRun() {
    if (!process.argv[1]) {
        return false;
    }

    return fileURLToPath(import.meta.url) === resolve(process.argv[1]);
}

async function main() {
    try {
        await verifyDatabaseConnection();
        console.log("Database connection ok.");
    } finally {
        await db.end();
    }
}

if (isDirectRun()) {
    main().catch((error: unknown) => {
        console.error(error instanceof Error ? error.message : error);
        process.exitCode = 1;
    });
}
