import pg from "pg";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import type { PoolConfig } from "pg";

const { Pool } = pg;
const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

function loadDotEnv(envPath = resolve(repositoryRoot, ".env")) {
    if (!existsSync(envPath)) {
        return;
    }

    const envFile = readFileSync(envPath, "utf8");

    for (const line of envFile.split(/\r?\n/)) {
        const trimmedLine = line.trim();

        if (!trimmedLine || trimmedLine.startsWith("#")) {
            continue;
        }

        const separatorIndex = trimmedLine.indexOf("=");

        if (separatorIndex === -1) {
            continue;
        }

        const key = trimmedLine.slice(0, separatorIndex).trim();
        let value = trimmedLine.slice(separatorIndex + 1).trim();

        if (!key || process.env[key] !== undefined) {
            continue;
        }

        if (
            (value.startsWith("\"") && value.endsWith("\"")) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            value = value.slice(1, -1);
        }

        process.env[key] = value;
    }
}

function configFromDatabaseUrl(databaseUrl: string): PoolConfig {
    const url = new URL(databaseUrl);
    const config: PoolConfig = {};

    if (url.hostname) {
        config.host = url.hostname;
    }

    if (url.port) {
        config.port = Number.parseInt(url.port, 10);
    }

    if (url.pathname && url.pathname !== "/") {
        config.database = decodeURIComponent(url.pathname.slice(1));
    }

    if (url.username) {
        config.user = decodeURIComponent(url.username);
    }

    if (url.password) {
        config.password = decodeURIComponent(url.password);
    }

    return config;
}

function getDatabaseConfig(): PoolConfig {
    loadDotEnv();

    const databaseUrl = process.env.DATABASE_URL?.trim();
    const config: PoolConfig = databaseUrl ? configFromDatabaseUrl(databaseUrl) : {};

    if (process.env.PGHOST) {
        config.host = process.env.PGHOST;
    }

    if (process.env.PGPORT) {
        config.port = Number.parseInt(process.env.PGPORT, 10);
    }

    if (process.env.PGDATABASE) {
        config.database = process.env.PGDATABASE;
    }

    if (process.env.PGUSER) {
        config.user = process.env.PGUSER;
    }

    if (process.env.PGPASSWORD !== undefined) {
        config.password = process.env.PGPASSWORD;
    }

    if (!config.connectionString && !config.database) {
        throw new Error("Set DATABASE_URL or PGDATABASE in the environment or .env file.");
    }

    return config;
}

export const db = new Pool(getDatabaseConfig());

type Migration = {
    version: number;
    name: string;
    sql: string;
};

const migrations: Migration[] = [
    {
        version: 1,
        name: "initial_context_schema",
        sql: `
            CREATE TABLE IF NOT EXISTS contexts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                kind TEXT NOT NULL DEFAULT 'note',
                content TEXT NOT NULL,
                source TEXT,
                tags TEXT[],
                created_at TIMESTAMPTZ NOT NULL,
                updated_at TIMESTAMPTZ NOT NULL
            );

            CREATE TABLE IF NOT EXISTS embeddings (
                context_id BIGINT PRIMARY KEY REFERENCES contexts(id) ON DELETE CASCADE,
                model TEXT,
                vector TEXT,
                created_at TIMESTAMPTZ,
                updated_at TIMESTAMPTZ
            );

            ALTER TABLE embeddings ADD COLUMN IF NOT EXISTS model TEXT;
            ALTER TABLE embeddings ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
            ALTER TABLE embeddings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

            CREATE INDEX IF NOT EXISTS contexts_created_at_idx
                ON contexts(created_at DESC, id DESC);

            CREATE INDEX IF NOT EXISTS contexts_tags_idx
                ON contexts USING GIN(tags);
        `,
    },
    {
        version: 2,
        name: "actor_attribution",
        sql: `
            CREATE TABLE IF NOT EXISTS actors (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                external_id TEXT,
                name TEXT NOT NULL,
                kind TEXT,
                metadata JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE UNIQUE INDEX IF NOT EXISTS actors_external_id_unique_idx
                ON actors(external_id)
                WHERE external_id IS NOT NULL;

            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS actor_id BIGINT;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'contexts_actor_id_fkey'
                      AND conrelid = 'contexts'::regclass
                ) THEN
                    ALTER TABLE contexts
                        ADD CONSTRAINT contexts_actor_id_fkey
                        FOREIGN KEY (actor_id)
                        REFERENCES actors(id)
                        ON DELETE SET NULL;
                END IF;
            END
            $$;

            CREATE INDEX IF NOT EXISTS contexts_actor_created_at_idx
                ON contexts(actor_id, created_at DESC, id DESC);
        `,
    },
    {
        version: 3,
        name: "context_visibility",
        sql: `
            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'whiteboard';

            ALTER TABLE contexts
                DROP CONSTRAINT IF EXISTS contexts_visibility_check;

            ALTER TABLE contexts
                ADD CONSTRAINT contexts_visibility_check
                CHECK (visibility IN ('whiteboard', 'channel', 'direct', 'personal', 'system'));

            CREATE INDEX IF NOT EXISTS contexts_visibility_created_at_idx
                ON contexts(visibility, created_at DESC, id DESC);
        `,
    },
    {
        version: 4,
        name: "authenticated_channels",
        sql: `
            CREATE TABLE IF NOT EXISTS actor_keys (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key_id TEXT NOT NULL UNIQUE,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                label TEXT,
                algorithm TEXT NOT NULL DEFAULT 'ed25519',
                public_key_pem TEXT NOT NULL,
                fingerprint_sha256 TEXT NOT NULL UNIQUE,
                status TEXT NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'revoked')),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                revoked_at TIMESTAMPTZ
            );

            CREATE INDEX IF NOT EXISTS actor_keys_actor_status_idx
                ON actor_keys(actor_id, status);

            CREATE TABLE IF NOT EXISTS auth_nonces (
                key_id TEXT NOT NULL REFERENCES actor_keys(key_id) ON DELETE CASCADE,
                nonce TEXT NOT NULL,
                used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                expires_at TIMESTAMPTZ NOT NULL,
                PRIMARY KEY (key_id, nonce)
            );

            CREATE INDEX IF NOT EXISTS auth_nonces_expires_at_idx
                ON auth_nonces(expires_at);

            CREATE TABLE IF NOT EXISTS channels (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                slug TEXT NOT NULL UNIQUE,
                name TEXT NOT NULL,
                description TEXT,
                created_by_actor_id BIGINT NOT NULL REFERENCES actors(id),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE IF NOT EXISTS channel_memberships (
                channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                role TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member')),
                can_read BOOLEAN NOT NULL DEFAULT TRUE,
                can_write BOOLEAN NOT NULL DEFAULT TRUE,
                joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                removed_at TIMESTAMPTZ,
                PRIMARY KEY (channel_id, actor_id)
            );

            CREATE INDEX IF NOT EXISTS channel_memberships_actor_active_idx
                ON channel_memberships(actor_id, channel_id)
                WHERE removed_at IS NULL;

            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS channel_id BIGINT;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'contexts_channel_id_fkey'
                      AND conrelid = 'contexts'::regclass
                ) THEN
                    ALTER TABLE contexts
                        ADD CONSTRAINT contexts_channel_id_fkey
                        FOREIGN KEY (channel_id)
                        REFERENCES channels(id)
                        ON DELETE RESTRICT;
                END IF;
            END
            $$;

            ALTER TABLE contexts
                DROP CONSTRAINT IF EXISTS contexts_visibility_scope_check;

            ALTER TABLE contexts
                ADD CONSTRAINT contexts_visibility_scope_check
                CHECK (
                    (visibility = 'channel' AND channel_id IS NOT NULL)
                    OR (visibility <> 'channel' AND channel_id IS NULL)
                );

            CREATE INDEX IF NOT EXISTS contexts_channel_created_at_idx
                ON contexts(channel_id, created_at DESC, id DESC)
                WHERE visibility = 'channel';
        `,
    },
    {
        version: 5,
        name: "approved_actor_sessions",
        sql: `
            CREATE TABLE IF NOT EXISTS actor_session_requests (
                request_id TEXT PRIMARY KEY,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                client_label TEXT,
                claim_secret_hash TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'approved', 'claimed', 'denied', 'expired')),
                requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                request_expires_at TIMESTAMPTZ NOT NULL,
                approved_at TIMESTAMPTZ,
                approved_session_ttl_seconds INTEGER,
                claimed_at TIMESTAMPTZ,
                denied_at TIMESTAMPTZ
            );

            CREATE INDEX IF NOT EXISTS actor_session_requests_status_expiry_idx
                ON actor_session_requests(status, request_expires_at);

            CREATE TABLE IF NOT EXISTS actor_sessions (
                session_id TEXT PRIMARY KEY,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                token_hash TEXT NOT NULL UNIQUE,
                client_label TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                expires_at TIMESTAMPTZ NOT NULL,
                last_used_at TIMESTAMPTZ,
                revoked_at TIMESTAMPTZ
            );

            CREATE INDEX IF NOT EXISTS actor_sessions_actor_active_idx
                ON actor_sessions(actor_id, expires_at)
                WHERE revoked_at IS NULL;

            CREATE TABLE IF NOT EXISTS actor_session_nonces (
                session_id TEXT NOT NULL REFERENCES actor_sessions(session_id) ON DELETE CASCADE,
                nonce TEXT NOT NULL,
                used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                expires_at TIMESTAMPTZ NOT NULL,
                PRIMARY KEY (session_id, nonce)
            );

            CREATE INDEX IF NOT EXISTS actor_session_nonces_expires_at_idx
                ON actor_session_nonces(expires_at);
        `,
    },
    {
        version: 6,
        name: "single_active_actor_session",
        sql: `
            ALTER TABLE actor_sessions
                ADD COLUMN IF NOT EXISTS predecessor_session_id TEXT,
                ADD COLUMN IF NOT EXISTS replaced_by_session_id TEXT,
                ADD COLUMN IF NOT EXISTS revocation_reason TEXT;

            WITH ranked AS (
                SELECT
                    session_id,
                    ROW_NUMBER() OVER (
                        PARTITION BY actor_id
                        ORDER BY created_at DESC, session_id DESC
                    ) AS active_rank
                FROM actor_sessions
                WHERE revoked_at IS NULL
            )
            UPDATE actor_sessions
            SET
                revoked_at = NOW(),
                revocation_reason = 'superseded_during_migration'
            FROM ranked
            WHERE actor_sessions.session_id = ranked.session_id
              AND ranked.active_rank > 1;

            CREATE UNIQUE INDEX IF NOT EXISTS actor_sessions_one_active_per_actor_idx
                ON actor_sessions(actor_id)
                WHERE revoked_at IS NULL;
        `,
    },
    {
        version: 7,
        name: "openai_tunnel_actor_sessions",
        sql: `
            ALTER TABLE actor_session_requests
                ADD COLUMN IF NOT EXISTS activation_pin_hash TEXT;

            ALTER TABLE actor_sessions
                ADD COLUMN IF NOT EXISTS openai_subject_hash TEXT,
                ADD COLUMN IF NOT EXISTS openai_session_hash TEXT;

            CREATE INDEX IF NOT EXISTS actor_sessions_openai_binding_idx
                ON actor_sessions(openai_subject_hash, openai_session_hash)
                WHERE openai_subject_hash IS NOT NULL
                  AND openai_session_hash IS NOT NULL;
        `,
    },
    {
        version: 8,
        name: "bind_openai_identity_at_session_request",
        sql: `
            ALTER TABLE actor_session_requests
                ADD COLUMN IF NOT EXISTS openai_subject_hash TEXT,
                ADD COLUMN IF NOT EXISTS openai_session_hash TEXT;
        `,
    },
    {
        version: 9,
        name: "access_groups",
        sql: `
            CREATE TABLE IF NOT EXISTS access_groups (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                slug TEXT NOT NULL UNIQUE,
                name TEXT NOT NULL,
                description TEXT,
                created_by_actor_id BIGINT NOT NULL REFERENCES actors(id),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE IF NOT EXISTS access_group_memberships (
                group_id BIGINT NOT NULL REFERENCES access_groups(id) ON DELETE CASCADE,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                role TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member')),
                can_read BOOLEAN NOT NULL DEFAULT TRUE,
                can_write BOOLEAN NOT NULL DEFAULT TRUE,
                joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                removed_at TIMESTAMPTZ,
                PRIMARY KEY (group_id, actor_id)
            );

            CREATE INDEX IF NOT EXISTS access_group_memberships_actor_active_idx
                ON access_group_memberships(actor_id, group_id)
                WHERE removed_at IS NULL;

            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS group_id BIGINT;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'contexts_group_id_fkey'
                      AND conrelid = 'contexts'::regclass
                ) THEN
                    ALTER TABLE contexts
                        ADD CONSTRAINT contexts_group_id_fkey
                        FOREIGN KEY (group_id)
                        REFERENCES access_groups(id)
                        ON DELETE RESTRICT;
                END IF;
            END
            $$;

            ALTER TABLE contexts
                DROP CONSTRAINT IF EXISTS contexts_visibility_check;

            ALTER TABLE contexts
                ADD CONSTRAINT contexts_visibility_check
                CHECK (visibility IN ('whiteboard', 'channel', 'direct', 'personal', 'system', 'group'));

            ALTER TABLE contexts
                DROP CONSTRAINT IF EXISTS contexts_visibility_scope_check;

            ALTER TABLE contexts
                ADD CONSTRAINT contexts_visibility_scope_check
                CHECK (
                    (visibility = 'channel' AND channel_id IS NOT NULL AND group_id IS NULL)
                    OR (visibility = 'group' AND group_id IS NOT NULL AND channel_id IS NULL)
                    OR (visibility NOT IN ('channel', 'group') AND channel_id IS NULL AND group_id IS NULL)
                );

            CREATE INDEX IF NOT EXISTS contexts_group_created_at_idx
                ON contexts(group_id, created_at DESC, id DESC)
                WHERE visibility = 'group';
        `,
    },
    {
        version: 10,
        name: "durable_attachments",
        sql: `
            CREATE TABLE IF NOT EXISTS attachments (
                id UUID PRIMARY KEY,
                original_filename TEXT NOT NULL,
                media_type TEXT NOT NULL,
                size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
                sha256 TEXT NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
                storage_key TEXT NOT NULL,
                owner_actor_id BIGINT REFERENCES actors(id) ON DELETE RESTRICT,
                group_id BIGINT REFERENCES access_groups(id) ON DELETE RESTRICT,
                created_by_actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE RESTRICT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CHECK (
                    (owner_actor_id IS NOT NULL AND group_id IS NULL)
                    OR (owner_actor_id IS NULL AND group_id IS NOT NULL)
                )
            );

            CREATE INDEX IF NOT EXISTS attachments_actor_created_at_idx
                ON attachments(owner_actor_id, created_at DESC)
                WHERE owner_actor_id IS NOT NULL;
            CREATE INDEX IF NOT EXISTS attachments_group_created_at_idx
                ON attachments(group_id, created_at DESC)
                WHERE group_id IS NOT NULL;
            CREATE INDEX IF NOT EXISTS attachments_storage_key_idx
                ON attachments(storage_key);

            CREATE TABLE IF NOT EXISTS attachment_uploads (
                id UUID PRIMARY KEY,
                original_filename TEXT NOT NULL,
                media_type TEXT NOT NULL,
                expected_size_bytes BIGINT NOT NULL CHECK (expected_size_bytes >= 0),
                expected_sha256 TEXT NOT NULL CHECK (expected_sha256 ~ '^[0-9a-f]{64}$'),
                received_size_bytes BIGINT NOT NULL DEFAULT 0 CHECK (received_size_bytes >= 0),
                owner_actor_id BIGINT REFERENCES actors(id) ON DELETE CASCADE,
                group_id BIGINT REFERENCES access_groups(id) ON DELETE CASCADE,
                created_by_actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                expires_at TIMESTAMPTZ NOT NULL,
                CHECK (
                    (owner_actor_id IS NOT NULL AND group_id IS NULL)
                    OR (owner_actor_id IS NULL AND group_id IS NOT NULL)
                )
            );

            CREATE INDEX IF NOT EXISTS attachment_uploads_expires_at_idx
                ON attachment_uploads(expires_at);

            CREATE TABLE IF NOT EXISTS context_attachments (
                context_id BIGINT NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
                attachment_id UUID NOT NULL REFERENCES attachments(id) ON DELETE CASCADE,
                relationship TEXT NOT NULL DEFAULT 'source'
                    CHECK (relationship IN ('source', 'derived', 'reference')),
                sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
                page_start INTEGER CHECK (page_start > 0),
                page_end INTEGER CHECK (page_end > 0),
                created_by_actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE RESTRICT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (context_id, attachment_id, relationship),
                CHECK (page_start IS NULL OR page_end IS NULL OR page_end >= page_start)
            );

            CREATE INDEX IF NOT EXISTS context_attachments_attachment_idx
                ON context_attachments(attachment_id, sort_order, context_id);
        `,
    },
    {
        version: 11,
        name: "context_acknowledgements",
        sql: `
            CREATE TABLE IF NOT EXISTS context_acknowledgements (
                context_id BIGINT NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                acknowledged_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (context_id, actor_id)
            );

            CREATE INDEX IF NOT EXISTS context_acknowledgements_actor_time_idx
                ON context_acknowledgements(actor_id, acknowledged_at, context_id);
        `,
    },
    {
        version: 12,
        name: "whiteboard_archive_history",
        sql: `
            ALTER TABLE contexts
                DROP CONSTRAINT IF EXISTS contexts_visibility_check;

            ALTER TABLE contexts
                ADD CONSTRAINT contexts_visibility_check
                CHECK (visibility IN (
                    'whiteboard', 'channel', 'direct', 'personal', 'system', 'group', 'archived'
                ));

            CREATE TABLE IF NOT EXISTS context_archives (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                context_id BIGINT NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
                reason TEXT NOT NULL CHECK (length(btrim(reason)) BETWEEN 1 AND 2000),
                archived_by_actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE RESTRICT,
                archived_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                restored_by_actor_id BIGINT REFERENCES actors(id) ON DELETE RESTRICT,
                restored_at TIMESTAMPTZ,
                CHECK (
                    (restored_by_actor_id IS NULL AND restored_at IS NULL)
                    OR (restored_by_actor_id IS NOT NULL AND restored_at IS NOT NULL)
                )
            );

            CREATE UNIQUE INDEX IF NOT EXISTS context_archives_one_active_idx
                ON context_archives(context_id)
                WHERE restored_at IS NULL;

            CREATE INDEX IF NOT EXISTS context_archives_time_idx
                ON context_archives(archived_at DESC, id DESC);
        `,
    },
    {
        version: 13,
        name: "attachment_audit_events",
        sql: `
            CREATE TABLE IF NOT EXISTS attachment_audit_events (
                id BIGSERIAL PRIMARY KEY,
                event_type TEXT NOT NULL,
                actor_id BIGINT REFERENCES actors(id) ON DELETE SET NULL,
                owner_actor_id BIGINT REFERENCES actors(id) ON DELETE SET NULL,
                group_id BIGINT REFERENCES access_groups(id) ON DELETE SET NULL,
                attachment_id UUID,
                upload_id UUID,
                size_bytes BIGINT CHECK (size_bytes IS NULL OR size_bytes >= 0),
                details JSONB NOT NULL DEFAULT '{}'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE INDEX IF NOT EXISTS attachment_audit_events_created_at_idx
                ON attachment_audit_events(created_at DESC, id DESC);
            CREATE INDEX IF NOT EXISTS attachment_audit_events_owner_idx
                ON attachment_audit_events(owner_actor_id, created_at DESC)
                WHERE owner_actor_id IS NOT NULL;
            CREATE INDEX IF NOT EXISTS attachment_audit_events_group_idx
                ON attachment_audit_events(group_id, created_at DESC)
                WHERE group_id IS NOT NULL;
        `,
    },
    {
        version: 14,
        name: "renewable_actor_session_leases",
        sql: `
            ALTER TABLE actor_sessions
                ADD COLUMN IF NOT EXISTS lease_expires_at TIMESTAMPTZ,
                ADD COLUMN IF NOT EXISTS last_renewed_at TIMESTAMPTZ,
                ADD COLUMN IF NOT EXISTS renewal_count INTEGER NOT NULL DEFAULT 0,
                ADD COLUMN IF NOT EXISTS credential_generation INTEGER NOT NULL DEFAULT 1,
                ADD COLUMN IF NOT EXISTS lifecycle_kind TEXT,
                ADD COLUMN IF NOT EXISTS external_deleted_at TIMESTAMPTZ,
                ADD COLUMN IF NOT EXISTS external_lifecycle_event_id TEXT;

            UPDATE actor_sessions
            SET
                lease_expires_at = COALESCE(lease_expires_at, expires_at),
                lifecycle_kind = COALESCE(
                    lifecycle_kind,
                    CASE
                        WHEN openai_subject_hash IS NOT NULL AND openai_session_hash IS NOT NULL
                            THEN 'trusted_openai_thread'
                        ELSE 'native_bearer'
                    END
                );

            ALTER TABLE actor_sessions
                ALTER COLUMN lease_expires_at SET NOT NULL,
                ALTER COLUMN lifecycle_kind SET NOT NULL;

            ALTER TABLE actor_sessions
                DROP CONSTRAINT IF EXISTS actor_sessions_lifecycle_kind_check;
            ALTER TABLE actor_sessions
                ADD CONSTRAINT actor_sessions_lifecycle_kind_check
                CHECK (lifecycle_kind IN ('trusted_openai_thread', 'native_bearer'));

            CREATE UNIQUE INDEX IF NOT EXISTS actor_sessions_external_lifecycle_event_idx
                ON actor_sessions(external_lifecycle_event_id)
                WHERE external_lifecycle_event_id IS NOT NULL;
        `,
    },
    {
        version: 15,
        name: "authorize_actor_session_renewal",
        sql: `
            ALTER TABLE actor_sessions
                ADD COLUMN IF NOT EXISTS renewal_enabled BOOLEAN NOT NULL DEFAULT FALSE;
            CREATE INDEX IF NOT EXISTS actor_sessions_actor_lease_idx
                ON actor_sessions(actor_id, lease_expires_at)
                WHERE revoked_at IS NULL;
        `,
    },
    {
        version: 16,
        name: "roost_sso_service_bindings",
        sql: `
            ALTER TABLE actor_session_requests
                ADD COLUMN IF NOT EXISTS federation_issuer TEXT,
                ADD COLUMN IF NOT EXISTS federation_audience TEXT;

            CREATE TABLE IF NOT EXISTS actor_session_service_bindings (
                binding_id TEXT PRIMARY KEY,
                source_session_id TEXT NOT NULL REFERENCES actor_sessions(session_id) ON DELETE CASCADE,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                issuer TEXT NOT NULL,
                audience TEXT NOT NULL,
                subject_hash TEXT NOT NULL,
                service_session_hash TEXT,
                binding_expires_at TIMESTAMPTZ NOT NULL,
                expires_at TIMESTAMPTZ NOT NULL,
                bound_at TIMESTAMPTZ,
                revoked_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (source_session_id, audience)
            );

            CREATE INDEX IF NOT EXISTS actor_session_service_bindings_lookup_idx
                ON actor_session_service_bindings(issuer, audience, subject_hash, service_session_hash)
                WHERE revoked_at IS NULL;
        `,
    },
    {
        version: 17,
        name: "roost_sso_explicit_handoff",
        sql: `
            ALTER TABLE actor_session_service_bindings
                ADD COLUMN IF NOT EXISTS service_subject_hash TEXT;

            CREATE INDEX IF NOT EXISTS actor_session_service_bindings_service_lookup_idx
                ON actor_session_service_bindings(
                    issuer, audience, service_subject_hash, service_session_hash
                )
                WHERE revoked_at IS NULL
                  AND service_subject_hash IS NOT NULL
                  AND service_session_hash IS NOT NULL;
        `,
    },
    {
        version: 18,
        name: "direct_context_inbox",
        sql: `
            CREATE TABLE IF NOT EXISTS direct_context_envelopes (
                sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                context_id BIGINT NOT NULL UNIQUE REFERENCES contexts(id) ON DELETE CASCADE,
                recipient_actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE INDEX IF NOT EXISTS direct_context_envelopes_recipient_sequence_idx
                ON direct_context_envelopes(recipient_actor_id, sequence DESC);

            CREATE INDEX IF NOT EXISTS direct_context_envelopes_recipient_time_idx
                ON direct_context_envelopes(recipient_actor_id, created_at DESC, sequence DESC);
        `,
    },
    {
        version: 19,
        name: "context_subjects",
        sql: `
            CREATE TABLE IF NOT EXISTS subjects (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                external_id TEXT NOT NULL UNIQUE
                    CHECK (external_id ~ '^subject:[a-z0-9][a-z0-9:_-]*$'),
                name TEXT NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 500),
                kind TEXT CHECK (kind IS NULL OR length(btrim(kind)) BETWEEN 1 AND 100),
                aliases TEXT[] NOT NULL DEFAULT '{}',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE INDEX IF NOT EXISTS subjects_name_idx
                ON subjects(lower(name));
            CREATE INDEX IF NOT EXISTS subjects_aliases_idx
                ON subjects USING GIN(aliases);

            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS subject_id BIGINT;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'contexts_subject_id_fkey'
                      AND conrelid = 'contexts'::regclass
                ) THEN
                    ALTER TABLE contexts
                        ADD CONSTRAINT contexts_subject_id_fkey
                        FOREIGN KEY (subject_id)
                        REFERENCES subjects(id)
                        ON DELETE RESTRICT;
                END IF;
            END
            $$;

            CREATE INDEX IF NOT EXISTS contexts_subject_created_at_idx
                ON contexts(subject_id, created_at DESC, id DESC)
                WHERE subject_id IS NOT NULL;
        `,
    },
    {
        version: 20,
        name: "immutable_context_payloads",
        sql: `
            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS payload_version INTEGER NOT NULL DEFAULT 1
                    CHECK (payload_version > 0);

            CREATE TABLE IF NOT EXISTS context_payloads (
                id TEXT PRIMARY KEY,
                context_id BIGINT NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
                version INTEGER NOT NULL CHECK (version > 0),
                kind TEXT NOT NULL CHECK (kind IN ('text')),
                media_type TEXT NOT NULL,
                text_content TEXT NOT NULL,
                size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (context_id, version)
            );

            INSERT INTO context_payloads (
                id, context_id, version, kind, media_type, text_content, size_bytes, created_at
            )
            SELECT
                'payload:context:' || contexts.id || ':v1',
                contexts.id,
                1,
                'text',
                'text/plain; charset=utf-8',
                contexts.content,
                octet_length(contexts.content),
                contexts.created_at
            FROM contexts
            ON CONFLICT (context_id, version) DO NOTHING;

            CREATE OR REPLACE FUNCTION context_payload_before_content_update()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.content IS DISTINCT FROM OLD.content THEN
                    NEW.payload_version := OLD.payload_version + 1;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE OR REPLACE FUNCTION context_payload_after_write()
            RETURNS TRIGGER AS $$
            BEGIN
                IF TG_OP = 'INSERT' OR NEW.content IS DISTINCT FROM OLD.content THEN
                    INSERT INTO context_payloads (
                        id, context_id, version, kind, media_type, text_content, size_bytes
                    ) VALUES (
                        'payload:context:' || NEW.id || ':v' || NEW.payload_version,
                        NEW.id,
                        NEW.payload_version,
                        'text',
                        'text/plain; charset=utf-8',
                        NEW.content,
                        octet_length(NEW.content)
                    );
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE OR REPLACE FUNCTION reject_context_payload_update()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'context payloads are immutable';
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS contexts_payload_before_update ON contexts;
            CREATE TRIGGER contexts_payload_before_update
                BEFORE UPDATE OF content ON contexts
                FOR EACH ROW EXECUTE FUNCTION context_payload_before_content_update();

            DROP TRIGGER IF EXISTS contexts_payload_after_insert ON contexts;
            CREATE TRIGGER contexts_payload_after_insert
                AFTER INSERT ON contexts
                FOR EACH ROW EXECUTE FUNCTION context_payload_after_write();

            DROP TRIGGER IF EXISTS contexts_payload_after_update ON contexts;
            CREATE TRIGGER contexts_payload_after_update
                AFTER UPDATE OF content ON contexts
                FOR EACH ROW EXECUTE FUNCTION context_payload_after_write();

            DROP TRIGGER IF EXISTS context_payloads_immutable ON context_payloads;
            CREATE TRIGGER context_payloads_immutable
                BEFORE UPDATE ON context_payloads
                FOR EACH ROW EXECUTE FUNCTION reject_context_payload_update();

            CREATE INDEX IF NOT EXISTS context_payloads_context_version_idx
                ON context_payloads(context_id, version DESC);
        `,
    },
    {
        version: 21,
        name: "context_connections",
        sql: `
            CREATE TABLE IF NOT EXISTS context_connections (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source_context_id BIGINT NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
                target_context_id BIGINT NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
                relationship TEXT NOT NULL
                    CHECK (relationship ~ '^[a-z][a-z0-9:_-]{0,63}$'),
                rationale TEXT
                    CHECK (rationale IS NULL OR length(btrim(rationale)) BETWEEN 1 AND 2000),
                created_by_actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE RESTRICT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CHECK (source_context_id <> target_context_id),
                UNIQUE (source_context_id, target_context_id, relationship)
            );

            CREATE OR REPLACE FUNCTION enforce_context_connection_scope()
            RETURNS TRIGGER AS $$
            DECLARE
                source_context contexts%ROWTYPE;
                target_context contexts%ROWTYPE;
            BEGIN
                SELECT * INTO source_context FROM contexts WHERE id = NEW.source_context_id;
                SELECT * INTO target_context FROM contexts WHERE id = NEW.target_context_id;

                IF source_context.id IS NULL OR target_context.id IS NULL THEN
                    RAISE EXCEPTION 'CONTEXT_NOT_FOUND_OR_NOT_AUTHORIZED';
                END IF;

                IF source_context.visibility NOT IN ('whiteboard', 'personal', 'channel', 'group')
                   OR target_context.visibility <> source_context.visibility
                   OR (source_context.visibility = 'personal'
                        AND target_context.actor_id IS DISTINCT FROM source_context.actor_id)
                   OR (source_context.visibility = 'channel'
                        AND target_context.channel_id IS DISTINCT FROM source_context.channel_id)
                   OR (source_context.visibility = 'group'
                        AND target_context.group_id IS DISTINCT FROM source_context.group_id) THEN
                    RAISE EXCEPTION 'CONTEXT_CONNECTION_SCOPE_MISMATCH';
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS context_connections_scope_guard ON context_connections;
            CREATE TRIGGER context_connections_scope_guard
                BEFORE INSERT OR UPDATE ON context_connections
                FOR EACH ROW EXECUTE FUNCTION enforce_context_connection_scope();

            CREATE INDEX IF NOT EXISTS context_connections_source_idx
                ON context_connections(source_context_id, created_at DESC, id DESC);
            CREATE INDEX IF NOT EXISTS context_connections_target_idx
                ON context_connections(target_context_id, created_at DESC, id DESC);
        `,
    },
    {
        version: 22,
        name: "context_lifecycle_metadata",
        sql: `
            ALTER TABLE contexts
                ADD COLUMN IF NOT EXISTS lifecycle_state TEXT NOT NULL DEFAULT 'active'
                    CHECK (lifecycle_state IN ('active', 'warm', 'cold', 'archive_candidate')),
                ADD COLUMN IF NOT EXISTS importance SMALLINT NOT NULL DEFAULT 50
                    CHECK (importance BETWEEN 0 AND 100),
                ADD COLUMN IF NOT EXISTS retrieval_count BIGINT NOT NULL DEFAULT 0
                    CHECK (retrieval_count >= 0),
                ADD COLUMN IF NOT EXISTS last_retrieved_at TIMESTAMPTZ,
                ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ,
                ADD COLUMN IF NOT EXISTS superseded_by_context_id BIGINT,
                ADD COLUMN IF NOT EXISTS lifecycle_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'contexts_superseded_by_context_id_fkey'
                      AND conrelid = 'contexts'::regclass
                ) THEN
                    ALTER TABLE contexts
                        ADD CONSTRAINT contexts_superseded_by_context_id_fkey
                        FOREIGN KEY (superseded_by_context_id)
                        REFERENCES contexts(id)
                        ON DELETE SET NULL;
                END IF;
            END
            $$;

            CREATE INDEX IF NOT EXISTS contexts_lifecycle_candidates_idx
                ON contexts(visibility, lifecycle_state, importance, lifecycle_updated_at, id)
                WHERE lifecycle_state IN ('cold', 'archive_candidate');
            CREATE INDEX IF NOT EXISTS contexts_last_retrieved_idx
                ON contexts(last_retrieved_at DESC NULLS LAST);
        `,
    },
    {
        version: 23,
        name: "auto_archive_evaluations",
        sql: `
            CREATE TABLE IF NOT EXISTS auto_archive_previews (
                token UUID PRIMARY KEY,
                actor_id BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
                candidate_ids BIGINT[] NOT NULL,
                policy JSONB NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                expires_at TIMESTAMPTZ NOT NULL,
                consumed_at TIMESTAMPTZ
            );

            CREATE TABLE IF NOT EXISTS auto_archive_evaluations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                preview_token UUID NOT NULL REFERENCES auto_archive_previews(token) ON DELETE CASCADE,
                context_id BIGINT NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
                eligible BOOLEAN NOT NULL,
                score INTEGER NOT NULL,
                reasons JSONB NOT NULL,
                protected_tags TEXT[] NOT NULL DEFAULT '{}',
                evaluated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE INDEX IF NOT EXISTS auto_archive_evaluations_context_idx
                ON auto_archive_evaluations(context_id, evaluated_at DESC, id DESC);
        `,
    },
    {
        version: 24,
        name: "artifact_payload_references",
        sql: `
            ALTER TABLE attachments
                ADD COLUMN IF NOT EXISTS payload_external_id TEXT;

            UPDATE attachments
            SET payload_external_id = 'payload:artifact:' || id || ':v1'
            WHERE payload_external_id IS NULL;

            ALTER TABLE attachments
                ALTER COLUMN payload_external_id SET NOT NULL;

            CREATE UNIQUE INDEX IF NOT EXISTS attachments_payload_external_id_idx
                ON attachments(payload_external_id);

            ALTER TABLE context_attachments
                DROP CONSTRAINT IF EXISTS context_attachments_relationship_check;
            ALTER TABLE context_attachments
                ADD CONSTRAINT context_attachments_relationship_check
                CHECK (relationship IN ('canonical', 'source', 'derived', 'reference'));
            ALTER TABLE context_attachments
                ADD COLUMN IF NOT EXISTS derived_from_attachment_id UUID
                    REFERENCES attachments(id) ON DELETE RESTRICT;
        `,
    },
];

let initializationPromise: Promise<void> | undefined;

export async function initializeDatabase() {
    initializationPromise ??= runDatabaseMigrations().catch((error) => {
        initializationPromise = undefined;
        throw error;
    });

    await initializationPromise;
}

export async function runDatabaseMigrations(pool: pg.Pool = db) {
    const client = await pool.connect();

    try {
        await client.query(`
            CREATE TABLE IF NOT EXISTS schema_migrations (
                version INTEGER PRIMARY KEY,
                name TEXT NOT NULL,
                applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        `);

        for (const migration of migrations) {
            await client.query("BEGIN");

            try {
                await client.query(
                    "SELECT pg_advisory_xact_lock(hashtext('personal-context-server-schema-migrations'))"
                );
                const applied = await client.query(
                    "SELECT 1 FROM schema_migrations WHERE version = $1",
                    [migration.version]
                );

                if (applied.rowCount === 0) {
                    await client.query(migration.sql);
                    await client.query(
                        "INSERT INTO schema_migrations (version, name) VALUES ($1, $2)",
                        [migration.version, migration.name]
                    );
                }

                await client.query("COMMIT");
            } catch (error) {
                await client.query("ROLLBACK");
                throw error;
            }
        }
    } finally {
        client.release();
    }
}

export async function verifyDatabaseConnection() {
    let client: pg.PoolClient;

    try {
        client = await db.connect();
    } catch (error) {
        if (
            error instanceof Error &&
            error.message.includes("client password must be a string")
        ) {
            throw new Error(
                "Postgres requires password authentication. Add a password to DATABASE_URL or set PGPASSWORD in the environment or .env file.",
                { cause: error }
            );
        }

        throw error;
    }

    try {
        await client.query("SELECT 1");
    } finally {
        client.release();
    }
}

function isDirectRun() {
    if (!process.argv[1]) {
        return false;
    }

    return fileURLToPath(import.meta.url) === resolve(process.argv[1]);
}

async function main() {
    try {
        await verifyDatabaseConnection();
        console.log("Database connection ok.");
    } finally {
        await db.end();
    }
}

if (isDirectRun()) {
    main().catch((error: unknown) => {
        console.error(error instanceof Error ? error.message : error);
        process.exitCode = 1;
    });
}
